### ISSUE TITLE
Alfworld 正负样本

### ISSUE THREAD

**Issue by swt-user** [Yifan-Song793/ETO#5]
非常感谢你们工作的开源！
当我们复现Alfworld的结果时，我们遇到了一些问题，无法复现出论文中的结果。我们发现在论文构造正负样本对时，会对负样本进行轮数cut。我们发现进行了这样的操作后，效果会下降，不进行该操作效果会更好。
![image](https://github.com/Yifan-Song793/ETO/assets/52394391/3b4e348c-52ce-4a05-8578-5d8e799b61ae)
想请教一下，你们实现论文中汇报的结果时采用的是哪一种策略。

**Comment by Yifan-Song793** [comment]
感谢你对我们工作的关注！ALFWorld 在构建正负样本对时无需进行负样本轮数 cut。论文报告的结果对应的原始代码只对 ScienceWorld 进行了轮数 cut。

**Comment by swt-user** [comment]
请问在ScienceWorld上进行轮数cut影响大吗，您有相关的消融实验数据可以借鉴嘛~

**Comment by Yifan-Song793** [comment]
抱歉，我们没有做过相关消融实验，ScienceWorld 进行轮数 cut 的原因是个别任务所需轮数很多（如 task-1-boil 和 task-10-measure-melting-point-(known-substance)），且最终的 action 往往是重复若干个动作检查状态（如温度、性状），如果不进行负样本 cut，则会导致正负样本之间轮数差过大
